name: TSETMC Telegram Filter Bot

on:
  schedule:
    - cron: '30 9 * * 0,1,2,3,6' # اجرای خودکار شنبه تا چهارشنبه ساعت ۱۳:۰۰ (پایان بازار)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: دانلود کدها
      uses: actions/checkout@v4

    - name: نصب پایتون
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: نصب کتابخانه‌ها
      run: |
        python -m pip install --upgrade pip
        pip install pytse-client pandas requests

    - name: اجرای فیلتر و ارسال به تلگرام
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python scraper.py
